export { COMPUTATION } from './types'
export { generateSpikingVectors } from './generateSpikingVectors'
export { getConfig } from './getConfig'
export { getConfigGPU } from './getConfigGPU'
export { getConfigCPU } from './getConfigCPU'